name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Step to clean up disk space
    - name: Clean up disk space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo apt-get clean

    # Step to install repo tool
    - name: Install repo tool
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 git curl
        sudo curl https://storage.googleapis.com/git-repo-downloads/repo -o /usr/local/bin/repo
        sudo chmod a+x /usr/local/bin/repo

    # Authenticate GitHub CLI with GH_TOKEN
    - name: Authenticate GitHub CLI
      env:
        GH_TOKEN: ${{ secrets.NEURAX }}
      run: gh auth login --with-token

    # Run the build script
    - name: AIO_GKI_build_kernel
      run: chmod +x AIO_GKI_build_kernel_release.sh && ./AIO_GKI_build_kernel_release.sh

    # Create the GitHub release
    - name: Create GitHub release
      env:
        GH_TOKEN: ${{ secrets.NEURAX }}
      run: |
        ZIP_FILES=($(find ./ -type f -name "*.zip"))
        REPO_OWNER="Uiugkhbkhbkg"
        REPO_NAME="GKI-KernelSU-SUSFS"
        TAG_NAME="v$(date +'%Y.%m.%d-%H%M%S')"
        RELEASE_NAME="GKI Kernels With KernelSU & SUSFS"
        RELEASE_NOTES="This release contains the following builds: $(printf '%s\n' "${ZIP_FILES[@]}")"

        echo "Creating GitHub release: $RELEASE_NAME..."
        gh release create "$TAG_NAME" "${ZIP_FILES[@]}" \
            --repo "$REPO_OWNER/$REPO_NAME" \
            --title "$RELEASE_NAME" \
            --notes "$RELEASE_NOTES"

        echo "GitHub release created with the following files:"
        printf '%s\n' "${ZIP_FILES[@]}"
