name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # Step to install repo tool
    - name: Install repo tool
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 git curl
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        echo 'export PATH=$HOME/bin:$PATH' >> ~/.bashrc
        source ~/.bashrc
    
    # Run the build script
    - name: AIO_GKI_build_kernel
      run: chmod +x AIO_GKI_build_kernel_release.sh && ./AIO_GKI_build_kernel_release.sh

    - name: Run a multi-line script
      run: |
        echo "Add other actions to build,"
        echo "test, and deploy your project."
